name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    # Note: Opting into Node 24 early to stay ahead of deprecations
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      # Mapping secrets here
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_LOCKED_OUT_USERNAME: ${{ secrets.SAUCE_LOCKED_OUT_USERNAME }}
      SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
      SAUCE_BASE_URL: ${{ secrets.SAUCE_BASE_URL }}
      BOOKER_API_URL: ${{ secrets.BOOKER_API_URL }}
      BOOKER_UI_URL: $ {{ secrets.BOOKER_UI_URL }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . # Changed from -r requirements.txt to .

    - name: Install Playwright Browsers
      run: playwright install --with-deps

    - name: Run Playwright tests
      run: pytest

    - name: Upload Report
      if: always() # This ensures reports upload even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: reports/
        retention-days: 30
